[package]
name = "farsight-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1"
bytes = "1"
farsight-net = { version = "0.1.0", path = "../net" }
farsight-proto = { version = "0.1.0", path = "../proto" }
opus = "0.4.0"
tokio = { version = "1.53", features = ["rt", "sync", "time", "macros"] }
tracing = "0.1"
