//! Keys as the server takes them: evdev codes. On Linux, winit's scancode
//! is the evdev code; elsewhere, the physical key is mapped by name.

use winit::keyboard::PhysicalKey;

#[cfg(target_os = "linux")]
pub fn evdev(key: PhysicalKey) -> Option<u32> {
    use winit::platform::scancode::PhysicalKeyExtScancode;
    key.to_scancode()
}

#[cfg(not(target_os = "linux"))]
pub fn evdev(key: PhysicalKey) -> Option<u32> {
    use winit::keyboard::KeyCode as K;
    let PhysicalKey::Code(code) = key else { return None };
    Some(match code {
        K::Escape => 1,
        K::Digit1 => 2,
        K::Digit2 => 3,
        K::Digit3 => 4,
        K::Digit4 => 5,
        K::Digit5 => 6,
        K::Digit6 => 7,
        K::Digit7 => 8,
        K::Digit8 => 9,
        K::Digit9 => 10,
        K::Digit0 => 11,
        K::Minus => 12,
        K::Equal => 13,
        K::Backspace => 14,
        K::Tab => 15,
        K::KeyQ => 16,
        K::KeyW => 17,
        K::KeyE => 18,
        K::KeyR => 19,
        K::KeyT => 20,
        K::KeyY => 21,
        K::KeyU => 22,
        K::KeyI => 23,
        K::KeyO => 24,
        K::KeyP => 25,
        K::BracketLeft => 26,
        K::BracketRight => 27,
        K::Enter => 28,
        K::ControlLeft => 29,
        K::KeyA => 30,
        K::KeyS => 31,
        K::KeyD => 32,
        K::KeyF => 33,
        K::KeyG => 34,
        K::KeyH => 35,
        K::KeyJ => 36,
        K::KeyK => 37,
        K::KeyL => 38,
        K::Semicolon => 39,
        K::Quote => 40,
        K::Backquote => 41,
        K::ShiftLeft => 42,
        K::Backslash => 43,
        K::KeyZ => 44,
        K::KeyX => 45,
        K::KeyC => 46,
        K::KeyV => 47,
        K::KeyB => 48,
        K::KeyN => 49,
        K::KeyM => 50,
        K::Comma => 51,
        K::Period => 52,
        K::Slash => 53,
        K::ShiftRight => 54,
        K::NumpadMultiply => 55,
        K::AltLeft => 56,
        K::Space => 57,
        K::CapsLock => 58,
        K::F1 => 59,
        K::F2 => 60,
        K::F3 => 61,
        K::F4 => 62,
        K::F5 => 63,
        K::F6 => 64,
        K::F7 => 65,
        K::F8 => 66,
        K::F9 => 67,
        K::F10 => 68,
        K::NumLock => 69,
        K::ScrollLock => 70,
        K::Numpad7 => 71,
        K::Numpad8 => 72,
        K::Numpad9 => 73,
        K::NumpadSubtract => 74,
        K::Numpad4 => 75,
        K::Numpad5 => 76,
        K::Numpad6 => 77,
        K::NumpadAdd => 78,
        K::Numpad1 => 79,
        K::Numpad2 => 80,
        K::Numpad3 => 81,
        K::Numpad0 => 82,
        K::NumpadDecimal => 83,
        K::IntlBackslash => 86,
        K::F11 => 87,
        K::F12 => 88,
        K::IntlRo => 89,
        K::NumpadEnter => 96,
        K::ControlRight => 97,
        K::NumpadDivide => 98,
        K::PrintScreen => 99,
        K::AltRight => 100,
        K::Home => 102,
        K::ArrowUp => 103,
        K::PageUp => 104,
        K::ArrowLeft => 105,
        K::ArrowRight => 106,
        K::End => 107,
        K::ArrowDown => 108,
        K::PageDown => 109,
        K::Insert => 110,
        K::Delete => 111,
        K::AudioVolumeMute => 113,
        K::AudioVolumeDown => 114,
        K::AudioVolumeUp => 115,
        K::NumpadEqual => 117,
        K::Pause => 119,
        K::NumpadComma => 121,
        K::IntlYen => 124,
        K::SuperLeft => 125,
        K::SuperRight => 126,
        K::ContextMenu => 127,
        K::F13 => 183,
        K::F14 => 184,
        K::F15 => 185,
        K::F16 => 186,
        K::F17 => 187,
        K::F18 => 188,
        K::F19 => 189,
        K::F20 => 190,
        K::F21 => 191,
        K::F22 => 192,
        K::F23 => 193,
        K::F24 => 194,
        _ => return None,
    })
}
