[package]
name = "farsight-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
bytes = "1"
clap = { version = "4.6.7", features = ["derive"] }
farsight-net = { version = "0.1.0", path = "../net" }
farsight-proto = { version = "0.1.0", path = "../proto" }
farsight-tiles = { version = "0.1.0", path = "../tiles" }
farsight-va = { version = "0.1.0", path = "../va" }
ffmpeg-sys-next = "9"
libc = "0.2.190"
libloading = "0.8"
smithay = { version = "0.7", default-features = false, features = ["backend_egl", "backend_gbm", "renderer_gl", "wayland_frontend", "desktop", "use_system_lib"] }
tokio = { version = "1.53", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
bindgen = "0.72"

[dev-dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
xkbcommon = "0.8"
